apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名字必需与下面的 spec 字段匹配，并且格式为 '<名称的复数形式>.<组名>'
  name: inferences.crd.example.com
  # https://kubernetes.io/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  # 组名称，用于 REST API: /apis/<组>/<版本>
  group: crd.example.com
  # 列举此 CustomResourceDefinition 所支持的版本
  versions:
    - name: v1
      # 每个版本都可以通过 served 标志来独立启用或禁止
      served: true
      # 其中一个且只有一个版本必需被标记为存储版本
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployment:
                  type: object
                  properties:
                    name:
                      type: string
                    image:
                      type: string
                    replicas:
                      type: integer
                      minimum: 1
                      maximum: 10
                    containerPort:
                      type: integer
                service:
                  type: object
                  properties:
                    name:
                      type: string
                ingress:
                  type: object
                  properties:
                    name:
                      type: string
                    urlPath:
                      type: string
                    className:
                      type: string
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
  names:
    # 名称的复数形式，用于 URL：/apis/<组>/<版本>/<名称的复数形式>
    plural: inferences
    # 名称的单数形式，作为命令行使用时和显示时的别名
    singular: inference
    # kind 通常是单数形式的驼峰命名（CamelCased）形式。你的资源清单会使用这一形式。
    kind: Inference
    # shortNames 允许你在命令行使用较短的字符串来匹配资源
    shortNames:
    - ifs
  scope: Namespaced
